
export const ALL_MODELS = [
    "/models/chapter-i/flower-transformed",
    "/models/chapter-i/gown-transformed",
    "/models/chapter-i/mannequin-transformed",
    "/models/chapter-ii/black_suit-transformed.glb",
    "/models/chapter-i/modern_mirror-transformed",
    "/models/chapter-ii/bottle-transformed.glb",
    "/models/chapter-ii/flute-transformed.glb",
    "/models/chapter-ii/retro_car-transformed.glb",
    "/models/chapter-ii/ztable-transformed.glb",
    "/models/chapter-iii/animated_drone-transformed.glb",
    "/models/chapter-iii/Camera_stand-transformed.glb",
    "/models/chapter-iii/couch-transformed.glb",
    "/models/chapter-iii/studio_umbrella-transformed.glb",
    "/models/chapter-iv/antique_table-transformed.glb",
    "/models/chapter-iv/elven_bracelet-transformed.glb",
    "/models/chapter-iv/heels-transformed.glb",
    "/models/chapter-iv/pillar-transformed.glb",
    "/models/chapter-iv/ring-transformed.glb",
    "/models/chapter-iv/three_gem_necklaces-transformed.glb",
    "/models/chapter-iv/vase_stand-transformed.glb",
    "/models/stage/djbooth-transformed.glb",
    "/models/stage/people.glb",
    "/models/stage/speakerequalizer-transformed.glb",
    "/models/stage/wardrobe-transformed.glb",
    "/models/stage/statue-transformed.glb",
]