/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/antique_table.glb --transform --output src/components/models/AntiqueTable.jsx 
Files: public/models/antique_table.glb [11.84MB] > C:\Users\G\Desktop\gown stage\src\components\models\antique_table-transformed.glb [1.79MB] (85%)
Author: Tyron (https://sketchfab.com/Omty)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/antique-table-f01054c29829452a9f87437de57a3f6f
Title: Antique Table
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AntiqueTable(props) {
  const { nodes, materials } = useGLTF('./models/chapter-iv/antique_table-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.defaultMat} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/chapter-iv/antique_table-transformed.glb')
