/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bottle.glb --transform --output src/components/models/Bottle.jsx 
Files: public/models/bottle.glb [4.14MB] > C:\Users\G\Desktop\gown stage\src\components\models\bottle-transformed.glb [513.25KB] (88%)
Author: GregoirePopineau (https://sketchfab.com/GregoirePopineau)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hoxxoh-gold-gold-f5ca5d956dcb45e7aa7de5b83881fe3c
Title: HOXXOH GOLD GOLD
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Bottle(props) {
  const { nodes, materials } = useGLTF('./models/bottle-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.LOWER} rotation={[-Math.PI / 2, 0, 0]} scale={0.007} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.007} />
    </group>
  )
}

useGLTF.preload('./models/bottle-transformed.glb')
