/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/elven_bracelet.glb --transform --output src/components/models/Bracelet.jsx 
Files: public/models/elven_bracelet.glb [3.82MB] > C:\Users\G\Desktop\gown stage\src\components\models\elven_bracelet-transformed.glb [331.59KB] (91%)
Author: allanoraphael (https://sketchfab.com/allanoraphael)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/elven-bracelet-cb66dd7fb7ca4154ac5613ff4946353b
Title: Elven Bracelet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Bracelet(props) {
  const { nodes, materials } = useGLTF('./models/chapter-iv/elven_bracelet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Bordas} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Ouro} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Pedras} />
    </group>
  )
}

useGLTF.preload('./models/chapter-iv/elven_bracelet-transformed.glb')
