/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Camera_stand.glb --transform --output src/components/models/CameraStand.jsx 
Files: public/models/Camera_stand.glb [307.13KB] > C:\Users\G\Desktop\gown stage\src\components\models\Camera_stand-transformed.glb [16.99KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CameraStand(props) {
  const { nodes, materials } = useGLTF('./models/chapter-iii/Camera_stand-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat22} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat23} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat25} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat8} />
    </group>
  )
}

useGLTF.preload('./models/chapter-iii/Camera_stand-transformed.glb')
