/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/retro_car.glb --transform --output src/components/models/Car.jsx 
Files: public/models/retro_car.glb [15.47MB] > C:\Users\G\Desktop\gown stage\src\components\models\retro_car-transformed.glb [1.96MB] (87%)
Author: pisarenok (https://sketchfab.com/pisarenok)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-car-2836e72f327f4d6f9fe836d646496927
Title: Retro Car
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Car(props) {
  const { nodes, materials } = useGLTF('./models/retro_car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Fars_Fars2_0.geometry} material={materials.Fars2} scale={0.01} />
      <mesh geometry={nodes.Fars1_Fars3_0.geometry} material={materials.Fars3} scale={0.01} />
      <mesh geometry={nodes.Window_Back_Glasses_0.geometry} material={materials.Glasses} scale={0.01} />
      <mesh geometry={nodes.Window_Back1_Glasses1_0.geometry} material={materials.Glasses1} scale={0.01} />
      <mesh geometry={nodes.Indicators_Ind_0.geometry} material={materials.material} scale={0.01} />
      <mesh geometry={nodes.Back1_low_Lincoln1_0.geometry} material={materials.Lincoln1} scale={0.01} />
      <mesh geometry={nodes.Foundation1_low_Lincoln2_0.geometry} material={materials.Lincoln2} scale={0.01} />
      <mesh geometry={nodes.Body1_low_Lincoln3_0.geometry} material={materials.Lincoln3} scale={0.01} />
      <mesh geometry={nodes.Mirrors_Wheels_Mirr_Wheels_0.geometry} material={materials.Mirr_Wheels} scale={0.01} />
      <mesh geometry={nodes.Mirrors_Roof_Mirr_0.geometry} material={materials.Mirr} scale={0.01} />
    </group>
  )
}

useGLTF.preload('./models/retro_car-transformed.glb')
