/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/couch.glb --transform --output src/components/models/Couch.jsx 
Files: public/models/couch.glb [5.9MB] > C:\Users\G\Desktop\gown stage\src\components\models\couch-transformed.glb [666.44KB] (89%)
Author: Visthétique (https://sketchfab.com/visthetique)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/delica-couch-be956580a9b5457aa811c73701a49419
Title: Delica Couch
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Couch(props) {
  const { nodes, materials } = useGLTF('./models/chapter-iii/couch-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DelicaCouch_LightFabric_0.geometry} material={materials.LightFabric} position={[0.333, 0.604, -0.072]} rotation={[-Math.PI / 2, 0, 0]} scale={0.348} />
      <mesh geometry={nodes.DelicaCouch_DarkerFabric_0.geometry} material={materials.DarkerFabric} position={[0.333, 0.604, -0.072]} rotation={[-Math.PI / 2, 0, 0]} scale={0.348} />
      <mesh geometry={nodes.DelicaCouch_Gold_0.geometry} material={materials.Gold} position={[0.333, 0.604, -0.072]} rotation={[-Math.PI / 2, 0, 0]} scale={0.348} />
    </group>
  )
}

useGLTF.preload('./models/chapter-iii/couch-transformed.glb')
