/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/djbooth.glb --transform --output src/components/models/DjBooth.jsx 
Files: public/models/djbooth.glb [548.79KB] > C:\Users\G\Desktop\gown stage\src\components\models\djbooth-transformed.glb [75.69KB] (86%)
Author: HumAi Club (https://sketchfab.com/2ndlr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dj-booth-15be961c0b4f446f988b77fa7693bde2
Title: DJ BOOTH
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function DjBooth(props) {
  const { nodes, materials } = useGLTF('/models/stage/djbooth-transformed.glb')
  return (
    <group {...props} dispose={null} rotation={[0, 0.9, 0]}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Circle.010_Bake1_baked.002']} position={[6.601, 1.661, -7.225]} rotation={[0, 0, -Math.PI]} scale={[0.032, 0.51, 0.032]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Loudspeaker_RGB_LIGHT} position={[6.419, 0.05, -6.226]} scale={[0.634, 0.061, 1.774]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Cube.022_Bake1_baked.001']} position={[6.403, 0.781, -7.743]} scale={[0.451, 0.491, 0.305]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Cube.018_Bake1_baked.001']} position={[6.419, 0.2, -6.226]} scale={[0.557, 0.061, 1.593]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.DJ_AUDIO_MIXER_BOOTH} position={[6.35, 0.838, -6.226]} scale={[0.415, 0.498, 0.852]} />
    </group>
  )
}

useGLTF.preload('/models/stage/djbooth-transformed.glb')
