/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/flower.glb --transform --output src/components/models/Flower.jsx 
Files: public/models/flower.glb [99.53MB] > C:\Users\G\Desktop\gown stage\src\components\models\flower-transformed.glb [9.72MB] (90%)
Author: Truong Arch (https://sketchfab.com/kiemtruongkts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flower-model-v001-351d63de2833444ab94f98ce1a7c239c
Title: Flower Model V.001
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Flower(props) {
  const { nodes, materials } = useGLTF('./models/flower-transformed.glb')
  return (
    <group {...props} dispose={null} >
      <lineSegments geometry={nodes.Material2_7.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3.geometry} material={materials['0003_DeepPink_2']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material4.geometry} material={materials['0003_DeepPink_2_0']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material5.geometry} material={materials['0003_DeepPink_2_1']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material8.geometry} material={materials['0003_DeepPink_2_4']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material9.geometry} material={materials['0003_DeepPink_2_5']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material6.geometry} material={materials['0003_DeepPink_2_2']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material7.geometry} material={materials['0003_DeepPink_2_3']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material12.geometry} material={materials['0003_DeepPink_2_8']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material13.geometry} material={materials['0003_DeepPink_2_9']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material14.geometry} material={materials['0003_DeepPink_2_10']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material15.geometry} material={materials['0003_DeepPink_2_11']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material10.geometry} material={materials['0003_DeepPink_2_6']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material11.geometry} material={materials['0003_DeepPink_2_7']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_1.geometry} material={materials['Flower-map3']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_2.geometry} material={materials['Flower-map5']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material4_1.geometry} material={materials['0003_DeepPink_2_12']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material5_1.geometry} material={materials['0003_DeepPink_2_13']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material6_1.geometry} material={materials['0003_DeepPink_2_14']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material8_1.geometry} material={materials['0003_DeepPink_2_16']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material7_1.geometry} material={materials['0003_DeepPink_2_15']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_1.geometry} material={materials['Flower-map2']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_3.geometry} material={materials['Flower-color3']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_4.geometry} material={materials['Flower-map1']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_5.geometry} material={materials['Flower-map4']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_6.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_8.geometry} material={materials.PaletteMaterial003} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_9.geometry} material={materials['0003_DeepPink']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/flower-transformed.glb')
