/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/flute.glb --transform --output src/components/models/Flute.jsx 
Files: public/models/flute.glb [2.17MB] > C:\Users\G\Desktop\gown stage\src\components\models\flute-transformed.glb [101.77KB] (95%)
Author: jaelynnmitchell (https://sketchfab.com/jaelynnmitchell)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mitchellj-simpleobjects-champagne-flute-e4efcf10ae654830b6aff6e3d70d6002
Title: MitchellJ_SimpleObjects_Champagne Flute
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Flute(props) {
  const { nodes, materials } = useGLTF('./models/flute-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/flute-transformed.glb')
