/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gown.glb --transform --output src/components/models/Gown.jsx 
Files: public/models/gown.glb [305.38KB] > C:\Users\G\Desktop\gown stage\src\components\models\gown-transformed.glb [35.81KB] (88%)
Author: Princess Gowns (https://sketchfab.com/smartcookie0909)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/princess-fiona-wedding-clothes-2477db82687f451489dc42e5681840e0
Title: Princess Fiona Wedding Clothes
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'
import { useAtomValue } from 'jotai'
import { activeChapterAtom } from '../../hooks/store'

export function Gown(props) {
  
  const { nodes, materials } = useGLTF('./models/chapter-i/gown-transformed.glb')
  const groupRef = useRef()

  useFrame((_, delta) => {
      groupRef.current.rotation.z += 0.5 * delta; 
  
  })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[0, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/chapter-i/gown-transformed.glb')
