/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/heels.glb --transform --output src/components/models/Heels.jsx 
Files: public/models/heels.glb [7.12MB] > C:\Users\G\Desktop\gown stage\src\components\models\heels-transformed.glb [2.56MB] (64%)
Author: hiirusama (https://sketchfab.com/hiirusama)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chain-strap-high-heels-87849936a0354a208cbbf80fbb2ccbe6
Title: Chain Strap High Heels
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";



export function Heels(props) {
  const { nodes, materials } = useGLTF('./models/chapter-iv/heels-transformed.glb')
  const groupRef = useRef()

  useFrame((_, delta)=>{
      groupRef.current.rotation.y += 0.5 * delta
  })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.Chain_Heels_sole_0.geometry} material={materials.sole} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Chain_Heels_silver_0.geometry} material={materials.silver} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/chapter-iv/heels-transformed.glb')
