/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mannequin.glb --transform --output src/components/models/Mannequin.jsx 
Files: public/models/mannequin.glb [1.74MB] > C:\Users\G\Desktop\gown stage\src\components\models\mannequin-transformed.glb [184.26KB] (89%)
Author: Aleksei Moskvin (https://sketchfab.com/alekseimoskvin1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mannequin-1900s-m-size-edce03ca9ee8410b8e0485504597389b
Title: Mannequin (1900s): M size
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Mannequin(props) {
  const { nodes, materials } = useGLTF('./models/mannequin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Avatar_Man2_0.geometry} material={materials.Man2} position={[1.5, 0, 0.5]} rotation={[0, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('./models/mannequin-transformed.glb')
