/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/three_gem_necklaces.glb --transform --output src/components/models/Necklaces.jsx 
Files: public/models/three_gem_necklaces.glb [16.05MB] > C:\Users\G\Desktop\gown stage\src\components\models\three_gem_necklaces-transformed.glb [1.53MB] (90%)
Author: MarkoJantti (https://sketchfab.com/MarkoJantti)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/three-gem-necklaces-3355abffbbaa44c3a6959b46c90dbd34
Title: Three Gem Necklaces
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Necklaces(props) {
  const { nodes, materials } = useGLTF('./models/chapter-iv/three_gem_necklaces-transformed.glb')
  const groupRef = useRef()

  useFrame((_, delta)=>{
    groupRef.current.rotation.y += 0.5 * delta
  })


  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.Necklace_Bust_Stand1_necklace_bust_stand_material002_0.geometry} material={materials['necklace_bust_stand_material.002']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Necklace03_Chain2_0.geometry} material={materials.Chain2} rotation={[-Math.PI / 2, 0, -2.094]} />
      <mesh geometry={nodes.Necklace03_Gem3_0.geometry} material={materials.Gem3} rotation={[-Math.PI / 2, 0, -2.094]} />
      <mesh geometry={nodes.Necklace01_Chain_0.geometry} material={materials.Chain} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Necklace01_Gem_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Necklace02_Gem2_0.geometry} material={materials.Gem2} rotation={[-Math.PI / 2, 0, 2.094]} />
    </group>
  )
}

useGLTF.preload('./models/chapter-iv/three_gem_necklaces-transformed.glb')
