/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pillar.glb --transform --output src/components/models/Pillar.jsx 
Files: public/models/pillar.glb [1.56MB] > C:\Users\G\Desktop\gown stage\src\components\models\pillar-transformed.glb [311.24KB] (80%)
Author: gaevinh (https://sketchfab.com/gaevinh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pillar-ac2eaeeccf9b4212a25c0df404551470
Title: Pillar
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Pillar(props) {
  const { nodes, materials } = useGLTF('./models/chapter-iv/pillar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('./models/chapter-iv/pillar-transformed.glb')
