/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ring.glb --transform --output src/components/models/Ring.jsx 
Files: public/models/ring.glb [3.67MB] > C:\Users\G\Desktop\gown stage\src\components\models\ring-transformed.glb [303.72KB] (92%)
Author: Rijo (https://sketchfab.com/Rijo_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ring-189e7478562b447a9d91b8fcc53d66e6
Title: Ring
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Ring(props) {
  const { nodes, materials } = useGLTF('./models/chapter-iv/ring-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material} position={[-0.002, 0.103, -0.007]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.glass} position={[-0.001, 0.083, 0.003]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Ring} position={[-0.001, 0.075, 0.003]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Leather.001']} position={[-0.001, 0.068, 0.003]} />
    </group>
  )
}

useGLTF.preload('./models/chapter-iv/ring-transformed.glb')
