/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/speakerequalizer.glb --transform --output src/components/models/Speaker.jsx 
Files: public/models/speakerequalizer.glb [4.58MB] > C:\Users\G\Desktop\gown stage\src\components\models\speakerequalizer-transformed.glb [620.08KB] (86%)
Author: s7ntech (https://sketchfab.com/s7ntech)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/speaker-with-equalizer-d9dd3d4213a8448b9999b3a57358e6d1
Title: Speaker with Equalizer
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export function Speaker(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/stage/speakerequalizer-transformed.glb')
  const { actions } = useAnimations(animations, group)

    useEffect(() => {
      if (actions['Animation']) {
        actions['Animation'].play()
      }
    }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="equalizer_35">
            <group name="baseCover001_0" position={[0, 1.797, 0]} rotation={[-Math.PI, 0, 0]} scale={[1.023, 1.804, 1.023]}>
              <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="glass_1">
              <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial002} />
            </group>
            <group name="indicator1_2" rotation={[-Math.PI, 0, 0]} scale={[1, 0.291, 1]}>
              <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator10_3" rotation={[-Math.PI, 0, 0]} scale={[1, 0.321, 1]}>
              <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator11_4" rotation={[-Math.PI, 0, 0]} scale={[1, 1.542, 1]}>
              <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator12_5" rotation={[-Math.PI, 0, 0]} scale={[1, 1.125, 1]}>
              <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator13_6" rotation={[-Math.PI, 0, 0]} scale={[1, 0.791, 1]}>
              <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator14_7" rotation={[-Math.PI, 0, 0]} scale={[1, 0.436, 1]}>
              <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator15_8" rotation={[-Math.PI, 0, 0]} scale={[1, 1.197, 1]}>
              <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator16_9" rotation={[-Math.PI, 0, 0]} scale={[1, 0.412, 1]}>
              <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator17_10" rotation={[-Math.PI, 0, 0]} scale={[1, 1.351, 1]}>
              <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator18_11" rotation={[-Math.PI, 0, 0]} scale={[1, 0.619, 1]}>
              <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator19_12" rotation={[-Math.PI, 0, 0]} scale={[1, 0.953, 1]}>
              <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator2_13" rotation={[-Math.PI, 0, 0]} scale={[1, 1.453, 1]}>
              <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator20_14" rotation={[-Math.PI, 0, 0]} scale={[1, 0.551, 1]}>
              <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator21_15" rotation={[-Math.PI, 0, 0]} scale={[1, 1.544, 1]}>
              <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator22_16" rotation={[-Math.PI, 0, 0]} scale={[1, 1.713, 1]}>
              <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator23_17" rotation={[-Math.PI, 0, 0]} scale={[1, 0.856, 1]}>
              <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator24_18" rotation={[-Math.PI, 0, 0]} scale={[1, 1.202, 1]}>
              <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator25_19" rotation={[-Math.PI, 0, 0]} scale={[1, 1.129, 1]}>
              <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator26_20" rotation={[-Math.PI, 0, 0]} scale={[1, 0.826, 1]}>
              <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator27_21" rotation={[-Math.PI, 0, 0]} scale={[1, 0.374, 1]}>
              <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator28_22" rotation={[-Math.PI, 0, 0]} scale={[1, 0.847, 1]}>
              <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator29_23" rotation={[-Math.PI, 0, 0]} scale={[1, 1.037, 1]}>
              <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator3_24" rotation={[-Math.PI, 0, 0]} scale={[1, 1.797, 1]}>
              <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator30_25" rotation={[-Math.PI, 0, 0]} scale={[1, 1.362, 1]}>
              <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator31_26" rotation={[-Math.PI, 0, 0]} scale={[1, 1.041, 1]}>
              <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator32_27" position={[0, 0.01, 0]} rotation={[-Math.PI, 0, 0]} scale={[1, 0.925, 1]}>
              <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator4_28" rotation={[-Math.PI, 0, 0]} scale={[1, 0.715, 1]}>
              <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator5_29" rotation={[-Math.PI, 0, 0]} scale={[1, 1.567, 1]}>
              <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator6_30" rotation={[-Math.PI, 0, 0]} scale={[1, 1.031, 1]}>
              <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator7_31" rotation={[-Math.PI, 0, 0]} scale={[1, 1.771, 1]}>
              <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator8_32" rotation={[-Math.PI, 0, 0]} scale={[1, 0.591, 1]}>
              <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.equalizer} />
            </group>
            <group name="indicator9_33" rotation={[-Math.PI, 0, 0]} scale={[1, 0.524, 1]}>
              <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.equalizer} />
            </group>
            <group name="linees_34" rotation={[-Math.PI, 0, 0]} scale={[0.99, 1.8, 0.99]}>
              <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.PaletteMaterial003} />
              <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials['Material.003']} />
            </group>
          </group>
        </group>
        <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.blackFabric} />
        <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.frontColor} />
        <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.blackInternal} />
        <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.PaletteMaterial003} />
        <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.PaletteMaterial001} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/stage/speakerequalizer-transformed.glb')
