/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/statue.glb --transform --output src/components/models/Statue.jsx 
Files: public/models/statue.glb [334.72KB] > C:\Users\G\Desktop\gown stage\src\components\models\statue-transformed.glb [76.16KB] (77%)
Author: Patrick Matthew (https://sketchfab.com/ungluedfire2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abstract-statue-decoration-5c58ccb0a5e74c94926a1eb2d507e937
Title: Abstract Statue Decoration
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Statue(props) {
  const { nodes, materials } = useGLTF('./models/stage/statue-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base_Metal_0.geometry} material={materials.Metal} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Foot1_Black_Metal_0.geometry} material={materials.Black_Metal} position={[0, 0.006, 0.04]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={[0.013, 0.004, 0.002]} />
    </group>
  )
}

useGLTF.preload('.models/stage/statue-transformed.glb')
