/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/studio_umbrella.glb --transform --output src/components/models/StudioUmbrella.jsx 
Files: public/models/studio_umbrella.glb [2.66MB] > C:\Users\G\Desktop\gown stage\src\components\models\studio_umbrella-transformed.glb [217.98KB] (92%)
Author: Glowbox 3D (https://sketchfab.com/glowbox3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/studio-umbrella-light-e3b19f2709084e22a628235fa0037556
Title: Studio Umbrella Light
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function StudioUmbrella(props) {
  const { nodes, materials } = useGLTF('./models/chapter-iii/studio_umbrella-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder003_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('./models/chapter-iii/studio_umbrella-transformed.glb')
