/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/black_suit.glb --transform --output src/components/models/Suit.jsx 
Files: public/models/black_suit.glb [11.55MB] > C:\Users\G\Desktop\gown stage\src\components\models\black_suit-transformed.glb [2.22MB] (81%)
Author: sxnneh (https://sketchfab.com/Sxnneh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-suit-aa409a429ecf4766b1c0e8c83fc15771
Title: Black Suit
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'

export function Suit(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('./models/black_suit-transformed.glb')

      useFrame((_, delta) => {
          groupRef.current.rotation.y += 0.5 * delta; 
      })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('./models/black_suit-transformed.glb')
