/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/table.glb --transform --output src/components/models/Table.jsx 
Files: public/models/table.glb [4.28MB] > C:\Users\G\Desktop\gown stage\src\components\models\table-transformed.glb [457.25KB] (89%)
Author: Mehdi Shahsavan (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-round-table-10mb-bcb7b6150606478db239210ab74212bb
Title: Wooden Round table - 10MB
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
  const { nodes, materials } = useGLTF('./models/table-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_Mat1_0.geometry} material={materials['Mat.1']} position={[0, 286.939, 0]} />
      <mesh geometry={nodes.Remesh_Mat_0.geometry} material={materials.material} />
    </group>
  )
}

useGLTF.preload('./models/table-transformed.glb')
