/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vanity.glb --transform --output src/components/models/Vanity.jsx 
Files: public/models/vanity.glb [2.43MB] > C:\Users\G\Desktop\gown stage\src\components\models\vanity-transformed.glb [76.16KB] (97%)
Author: dion.manganiello (https://sketchfab.com/dion.manganiello)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vanity-householdpropschallenge-3c2f06ba77994ee18527ec85003f7c47
Title: Vanity #HouseholdPropsChallenge
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Vanity(props) {
  const { nodes, materials } = useGLTF('/models/vanity-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.PaletteMaterial003} position={[0, 0, 399.85]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.PaletteMaterial004} position={[0, 750, -200]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.PaletteMaterial005} position={[0, 750, -200]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/vanity-transformed.glb')
