/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vase_stand.glb --transform --output src/components/models/VaseStand.jsx 
Files: public/models/vase_stand.glb [19.37MB] > C:\Users\G\Desktop\gown stage\src\components\models\vase_stand-transformed.glb [1.2MB] (94%)
Author: Modenese Gastone Interiors (https://sketchfab.com/modeneseinteriors)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/12671-vase-stand-modenese-gastone-bc5c9170f3a742459039655aa6751553
Title: 12671 Vase Stand - Modenese Gastone
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function VaseStand(props) {
  const { nodes, materials } = useGLTF('./models/chapter-iv/vase_stand-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle001_Gold_Grunge_0.geometry} material={materials.Gold_Grunge} position={[0, 0.872, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('./models/chapter-iv/vase_stand-transformed.glb')
