/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vintage_camera.glb --transform --output src/components/models/VintageCamera.jsx 
Files: public/models/vintage_camera.glb [6.13MB] > C:\Users\G\Desktop\gown stage\src\components\models\vintage_camera-transformed.glb [327.97KB] (95%)
Author: sh.tripathipankaj (https://sketchfab.com/sh.tripathipankaj)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-camera-c1ae384218d14636be6fdfe2ac8414a4
Title: Vintage Camera
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function VintageCamera(props) {
  const { nodes, materials } = useGLTF('./models/vintage_camera-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_1_Clear_Glass_0.geometry} material={materials.Clear_Glass} position={[1.362, 0.028, 0.681]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_2_Glossy_Black_0.geometry} material={materials.Glossy_Black} position={[-0.347, -0.034, -0.519]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_3__0.geometry} material={materials.Cylinder_3__0} position={[0.881, -0.353, -0.524]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes['Extrude_Gold_-_Macro_Scratches_0'].geometry} material={materials['Gold_-_Macro_Scratches']} position={[0.881, -0.353, -0.537]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('./models/vintage_camera-transformed.glb')
