/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/wardrobe.glb --transform --output src/components/models/Wardrobe.jsx 
Files: public/models/wardrobe.glb [21.79MB] > C:\Users\G\Desktop\gown stage\src\components\models\wardrobe-transformed.glb [1.44MB] (93%)
Author: InvisiblePolygon (https://sketchfab.com/InvisiblePolygon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wardrobe-with-vinatge-clothes-40d4d44217564817b6f00977901dc19f
Title: Wardrobe with vinatge clothes
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Wardrobe(props) {
  const { nodes, materials } = useGLTF('/models/wardrobe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wardrobe_Material001_0.geometry} material={materials['Material.001']} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.hanger_1_hanger1_0.geometry} material={materials.hanger1} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.shirt4_tshirt_brown_0.geometry} material={materials.tshirt_brown} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.shirt3_tshirt_purple_0.geometry} material={materials.tshirt_purple} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.shirt8_tshirt_red_0.geometry} material={materials.tshirt_red} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.shirtl4_tshirtLyellow_0.geometry} material={materials.material_0} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.shirtl2_shirtLblue_0.geometry} material={materials.shirtLblue} position={[-4.726, 0, 0]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/wardrobe-transformed.glb')
