/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ztable.glb --transform --output src/components/models/Ztable.jsx 
Files: public/models/ztable.glb [116.03KB] > C:\Users\G\Desktop\gown stage\src\components\models\ztable-transformed.glb [8.7KB] (93%)
Author: d-luX (https://sketchfab.com/dluX80)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dlx-luxury-z-champagne-6669b502031846d99d95476e1e859ae9
Title: dlX - Luxury Z Champagne
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Ztable(props) {
  const { nodes, materials } = useGLTF('./models/chapter-ii/ztable-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['dlX_-_Luxury_Z_Champagne_champagne_0'].geometry} material={materials.champagne} scale={0.01} />
      <mesh geometry={nodes['dlX_-_Luxury_Z_Champagne_silver_0'].geometry} material={materials.silver} scale={0.01} />
    </group>
  )
}

useGLTF.preload('./models/chapter-ii/ztable-transformed.glb')
